[build]
  command = "gatsby build && cd functions/node-fetch-goodreads && yarn && cd ../functions/node-fetch-author && yarn && cd ../functions/node-fetch-twitter && yarn"
  functions = "functions"
  publish = "public"