[build]
  command = "gatsby build && cd functions/node-fetch-goodreads && yarn && cd ../node-fetch-author && yarn && cd ../node-fetch-twitter && yarn"
  functions = "functions"
  publish = "public/"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"